globalvar DIR, BATTLE;
DIR = {
	UP: 180,
	DOWN: 0,
	LEFT: 270,
	RIGHT: 90
}

BATTLE = {
	STATE:{
		MENU: "MENU",
		DIALOG: "DIALOG",
		TURNPREPARATION: "TURNPREPARATION",
		INTURN: "INTURN",
		BOARDRESETTING: "BOARDRESETTING",
		RESULT: "RESULT",
		FLEE: "FLEE"
	},MENU:{
		BUTTON: "BUTTON",
		ENEMY: "ENEMY",
		FIGHTAIM: "FIGHTAIM",
		FIGHTANIM: "FIGHTANIM",
		FIGHTDAMAGE: "FIGHTDAMAGE",
		ACT: "ACT",
		ITEM: "ITEM",
		MERCY: "MERCY"
	}
}
